# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intent_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'intent_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14intent_service.proto\x12\x12intent_classify.v1\" \n\rIntentRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"D\n\x0eIntentResponse\x12\x0e\n\x06intent\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0e\n\x06reason\x18\x03 \x01(\t2l\n\rIntentService\x12[\n\x10IntentRecognizer\x12!.intent_classify.v1.IntentRequest\x1a\".intent_classify.v1.IntentResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intent_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INTENTREQUEST']._serialized_start=44
  _globals['_INTENTREQUEST']._serialized_end=76
  _globals['_INTENTRESPONSE']._serialized_start=78
  _globals['_INTENTRESPONSE']._serialized_end=146
  _globals['_INTENTSERVICE']._serialized_start=148
  _globals['_INTENTSERVICE']._serialized_end=256
# @@protoc_insertion_point(module_scope)
